### ISSUE TITLE
Update to dashboard 2.0

### ISSUE THREAD

**Issue by ryangonzalez133** [MaddyTP/node-red-contrib-ui-reef#1]
Hello friend, great work done by you, I would like to know if it is possible to update to dashboard 2.0?

**Comment by MaddyTP** [comment]
Let me look into the new dashboard...I wasn't aware they released a new major version.

**Comment by ryangonzalez133** [comment]
ok friend, thanks. The standard dashboard has been discontinued, there is now sse 2.0

**Comment by ryangonzalez133** [comment]
Hello, any news?

**Comment by MaddyTP** [comment]
> Hello, any news?

I've begun porting the solution over to Dashboard 2, however it will require a new repo due to their naming convention requirements.  It'll take me a few weeks to get it ported over since I'm only working on it in my off time.

**Comment by ryangonzalez133** [comment]
Ok friend, I just wanted to know if the upgrade would be possible. Thanks for the work

**Comment by MaddyTP** [comment]
Published!

[@maddytp/node-red-dashboard-2-ui-reef](https://github.com/MaddyTP/node-red-dashboard-2-ui-reef)

I took the opportunity to update several features and included a new node I never got around to in this repo.  The biggest change is with the ui-output node which now operates like the function node on `msg` input instead of interval.

**Comment by ryangonzalez133** [comment]
Thank you my friend, your work was great. I use it to monitor my nano reef. For now I only have basic control of the nano, such as temperature and water replacement, I use the probe and the output. But the work was very good, congratulations, I will finish implementing it in my system.
